name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
          POSTGRES_DB: django_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U django"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        # If your Django project (manage.py) is inside a subfolder, set working-directory here
        working-directory: ./your-django-folder

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
        # Note: `../requirements.txt` assumes requirements.txt is in root, not in the subfolder

      - name: Run migrations
        run: python manage.py migrate

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Run tests
        run: python manage.py test 

      # You can add a deploy step here if needed

